### ISSUE TITLE
Instance index should be a label not a metric

### ISSUE THREAD

**Issue by william0mayo** [cloudfoundry-community/stackdriver-tools#100]
Currently the container metric's "instance index" is being sent as a separate metric type. It should really be a label on the other container metrics. (E.g. This is the CPU utilization for this instance of this app)

**Comment by johnsonj** [comment]
Thanks! Good catch 

- [offending code](https://github.com/cloudfoundry-community/stackdriver-tools/blob/master/src/stackdriver-nozzle/nozzle/metric_sink.go#L65)

We should emit it as a label.

**Comment by johnsonj** [comment]
The initial fix was rolled back but #136 will resolve this

**Comment by johnsonj** [comment]
Released as [v2.0.1](https://github.com/cloudfoundry-community/stackdriver-tools/releases/tag/v2.0.1).
