### ISSUE TITLE
Uses deprecated version of Golang

### ISSUE THREAD

**Issue by bradylove** [cloudfoundry-community/stackdriver-tools#173]
It looks like the nozzle has not kept up with newer versions of Go. It has 1.7.1 and still has golang 1.6 blob.

/cc @apoydence

**Comment by johnsonj** [comment]
This is [fixed](https://github.com/cloudfoundry-community/stackdriver-tools/commit/abf5077824db203fc80c4d9ec11c274c296e515f) in [develop](https://github.com/cloudfoundry-community/stackdriver-tools/tree/develop)
