### ISSUE TITLE
Provide Bosh 2.0 manifest.

### ISSUE THREAD

**Issue by bradylove** [cloudfoundry-community/stackdriver-tools#174]
It would be convenient to have a Bosh 2.0 manifest available for deployments.

This would remove the need for the Bosh 1 CLI that supports ERB as well as allow users to take advantage of vars files and store.

/cc @apoydence

**Comment by johnsonj** [comment]
[Manifest](https://github.com/cloudfoundry-community/stackdriver-tools/blob/develop/manifests/stackdriver-tools.yml) has been updated
