### ISSUE TITLE
Run a single instance of the nozzle

### ISSUE THREAD

**Issue by knyar** [cloudfoundry-community/stackdriver-tools#190]
Counter support in the nozzle [requires deterministic routing](https://docs.google.com/document/d/1pU1FWpV86ZtnjEaxSiIsgw-5Dx5IjUc6Jav5WN8Ib7s/edit#) of loggregator metric events to nozzle instances. This [might eventually](https://www.pivotaltracker.com/n/projects/993188/stories/154821450) be implemented in Loggregator V2 API, but until that is done (and we switch to V2), we need to change the tile to restrict the number of nozzle instances to 1 (currently default is 2, and the value can be changed by the user).

**Comment by johnsonj** [comment]
Does this include scaling the logging pipeline separately from the metric pipeline?

**Comment by knyar** [comment]
I'd suggest we keep a single nozzle bosh job for now, since:
- a single nozzle instance is sufficient for the Cloud Ops team (which seem to be the biggest user).
- a single nozzle job is easier to operate (monitor, etc).
- we have (sort of) a clear path to be able to scale the nozzle horizontally when the change mentioned above lands in Loggregator.

**Comment by johnsonj** [comment]
Sounds good. Thanks!
