### ISSUE TITLE
Log Message is Duplicated

### ISSUE THREAD

**Issue by pivotalsquid** [cloudfoundry-community/stackdriver-tools#209]
We're using the Stackdriver Nozzle to get logs from our application running on CloudFoundry into Stackdriver.

Viewing the logs coming straight out of PCF, I get a structure like the following:

```
{
  "timestamp": "…",
  "source_id": "…",
  "instance_id": "…",
  "deprecated_tags": {…},
  "tags": {
    "deployment": "…",
    "index": "…",
    "ip": "…",
    "job": "…",
    "origin": "…",
    "source_type": "…"
  },
  "log": {
    "payload": "Base64encoded..."
  }
}
```

Viewing this same log in Stackdriver, I see this structure:
```
{
 insertId:  "…"  
 jsonPayload: {
  deployment:  "…"   
  eventType:  "…"   
  index:  "…"   
  ip:  "…"   
  job:  "…"   
  logMessage: {
   app_id:  "…"    
   message:  "Base64encoded..."    
   message_type:  "…"    
   source_instance:  "…"    
   source_type:  "…"    
   timestamp:  …    
  }
  message:  "Base64encoded..."   
  origin:  "…"   
  serviceContext: {…}   
  tags: {
   source_id:  "…"    
  }
  timestamp:  …   
 }
 labels: {…}  
 logName:  "…"  
 receiveTimestamp:  "…"  
 resource: {…}  
 timestamp:  "…"  
}
```

Notice how the `log.payload` from PCF is duplicated in 2 places by the time it gets into Stackdriver, In the `jsonPayload.logMessage.message` and `jsonPayload.message` fields.

Is this intentional? If so, why? It has caused a bit of confusion - which `message` field should we be using? We are also wondering that this duplication may be increasing our Stackdriver and BigQuery storage costs.

**Comment by mattysweeps** [comment]
This was merged to master via #211
