### ISSUE TITLE
Specify dependency on PAS tile

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-community/stackdriver-tools#216]
I saw that the stackdriver nozzel tile 2.0.1 is missing requires_product_versions, it is set in the tile-generator/tile.yml file but missing from metadata/stackdriver-nozzle.yml, also according to tile-generator/version the tile was generated with 11.0.5 which is quite old. When I tried myself with 12.0.8 and tile-generator/tile.yml the requires_product_versions where specified in metadata/stackdriver-nozzle.yml.

**Comment by mattysweeps** [comment]
Addressed in v2.1.0
