### ISSUE TITLE
release-v2.1.0

### ISSUE THREAD

**Issue by mattysweeps** [cloudfoundry-community/stackdriver-tools#228]
# Release Process

## Before continuing

- [x] `make lint build test bosh-release tile` runs successfully 
- [x] The system should build and all tests pass with the Concourse pipeline.
- [x] Open a ticket with the name `release-vX.Y.Z` and copy the contents of this file into its description.
- [x] Create a new pre-release branch in the GitHub repository labeled `release-vX.Y.Z`.

## Update the project in the branch

- [x] Update the `CHANGELOG.md` to match the new version.
- [x] Ensure `tile.yml.erb` is using the correct PCF version dependencies.
- [x] Commit the changes on the new branch.

## Our repository

- [x] Draft a new release in GitHub with the tag `vX.Y.Z-rc`
- [x] Include the version's changelog entry in the description.
- [x] Upload the built tile and BOSH release to the pre-release.
- [x] Check the box labeled **This is a pre-release**.
- [x] Publish the pre-release.

## Release on PivNet

- [x] Validate that the name in the generated tile's `metadata.yml` matches the slug on PivNet.
- [x] Ensure the release version is consistent on the tile and documentation.
- [x] Create a [new release on PivNet](network.pivotal.io) as an Admin Only release.
- [x] Upload the tile and BOSH release that were staged to GitHub.
- [x] Check that the tile passes the tests in the [build dashboard](https://tile-dashboard.cfapps.io/tiles/gcp-service-broker).

## Upgrade the documentation

- [x] Submit a pull request to the [documentation repository](https://github.com/pivotal-cf/docs-google/tree/master/docs-content).
- [x] Include the new release notes, changes, and the ERT/PAS and Ops Managers versions, as well as your Product Version and Release Date in the Product Snapshot on PivNet.

## File for release

- [x] Fill out the [release form](https://docs.google.com/forms/d/e/1FAIpQLSctLGMU8iOuwq6NqDYI65aMhJ7widDQGo9SawDG0b8TFfq7Ag/viewform).
- [x] An ISV Program Manager will make the release available to "All Users" after review. Partner Admins can make the release available to "Admin Users".
- [x] Merge the release branch once done.
- [ ] Submit an issue to https://github.com/cf-platform-eng/gcp-pcf-quickstart to update the GCP PCF quickstart.

**Comment by evandbrown** [comment]
Thanks, @mattysweeps! A few things:

- [ ] Is `2.3.0` the right version? The last release was `2.0.1`. 
- [ ] Versions in `metadata/stackdriver-nozzle.yml` (inside the `.pivotal` file) currently have an `-rc` prefix. The `-rc` suffix should only be used in the description/tags on GitHub, and should be omitted from the tile itself.

**Comment by mattysweeps** [comment]
@evandbrown the `-rc` suffix should be removed in `2.3.0-rc2` https://github.com/cloudfoundry-community/stackdriver-tools/releases/tag/v2.3.0-rc2

Yes, `2.3.0` is the correct version. To my knowledge, no backwards incompatible tile configuration or behavior (except the removal of the duplication of the log message) has been added. And `2.3.0` is a close and convenient minor bump to use since it pairs itself with PCF 2.3 support.

The decision process and/or the ABI coverage we choose for tile versioning can be improved and better defined for later releases.

**Comment by evandbrown** [comment]
Cool! So did we use `2.1.0` and `2.2.0` in releases that didn't make it to Pivnet?

**Comment by mattysweeps** [comment]
No, I just think it should be 2.3.0

**Comment by evandbrown** [comment]
Since we're following semver shouldn't we bump minor and call this `2.1.0`? I don't think we want to conflate the tile version with support for a particular version of PAS.

**Comment by mattysweeps** [comment]
@evandbrown I've changed the version to `2.1.0` per your request: https://github.com/cloudfoundry-community/stackdriver-tools/releases/tag/v2.1.0-rc

**Comment by mattysweeps** [comment]
@evandbrown see https://github.com/cloudfoundry-community/stackdriver-tools/releases/tag/v2.1.0-rc2

**Comment by mattysweeps** [comment]
2.1.0 is released: 

https://github.com/cloudfoundry-community/stackdriver-tools/releases/tag/v2.1.0
https://network.pivotal.io/products/gcp-stackdriver-nozzle/#/releases/282380
