### ISSUE TITLE
rpc error: code = 13 desc = stream terminated by RST_STREAM with error code: 2

### ISSUE THREAD

**Issue by claudio-benfatto** [cloudfoundry-community/stackdriver-tools#72]
Hello,

I am using the nozzle in combination with google cloud stackdriver. In our logs we keep seeing the following errors:

```
rpc error: code = 13 desc = stream terminated by RST_STREAM with error code: 2"
```

our configuration looks like this:

```
    export FIREHOSE_ENDPOINT=https://api.our.domain.io
    export FIREHOSE_USERNAME=firehose
    export FIREHOSE_PASSWORD=password
    export FIREHOSE_EVENTS=LogMessage,Error,HttpStartStop,CounterEvent,ValueMetric,ContainerMetric
    export FIREHOSE_SKIP_SSL=false
    export FIREHOSE_SUBSCRIPTION_ID=stackdriver-nozzle
    export FIREHOSE_NEWLINE_TOKEN=

    export DEBUG_NOZZLE=true
    export RESOLVE_APP_METADATA=true
```

could you help with this problem?

Many thanks,
Claudio

**Comment by johnsonj** [comment]
Hi Claudio!

This is a known issue and will be fixed by #62. We're reporting metrics too often so they get dropped by Stackdriver.

**Comment by johnsonj** [comment]
Closing as dup of #62. Please re-open if there's more to it.

**Comment by claudio-benfatto** [comment]
Thanks @johnsonj ! I'll follow the other issue.

**Comment by johnsonj** [comment]
@claudio-benfatto - This fix is now integrated into the GA release on [PivNet](https://network.pivotal.io/products/gcp-stackdriver-nozzle/#/releases/4882) and [GitHub](https://github.com/cloudfoundry-community/stackdriver-tools/releases/tag/v1.0.2)
