### ISSUE TITLE
Add new dependency in OSS disclosure 

### ISSUE THREAD

**Issue by johnsonj** [cloudfoundry-community/stackdriver-tools#77]
From PR #76 - github.com/mitchellh/hashstructure

**Comment by evandbrown** [comment]
If this is a pain in the ass _in the slightest_ I can yank that dependency and hash those values by hand, it's super super simple.

**Comment by johnsonj** [comment]
Just a copy & paste, no big deal. Just need to make sure it's tracked.

**Comment by johnsonj** [comment]
Dependency not added
