### ISSUE TITLE
Add monitoring roles to documentation

### ISSUE THREAD

**Issue by johnsonj** [cloudfoundry-community/stackdriver-tools#82]
The current suggested roles do not allow the stackdriver-agent to setup/write metrics. Today it needs an 'Editor' role to write metrics. Additionally it seems like the agent does configuration that requires the 'Owner' role on first start. 

* [Monitoring Roles](https://cloud.google.com/monitoring/access-control)
* [Logging Roles](https://cloud.google.com/logging/docs/access-control)

Provide a snippet to create a service account and add appropriate roles. Similar to the [example app](https://github.com/cloudfoundry-community/stackdriver-tools/tree/master/examples/cf-stackdriver-example#setting-up-iam-permissions).

**Comment by xoebus** [comment]
Ended up needing to add the `roles/monitoring.metricWriter` role. After that the "Editor" could be removed. This was only possible through the CLI at the moment as the "Monitoring/*" roles were not in the Web UI.

**Comment by johnsonj** [comment]
Thanks for working with me to identify the proper roles!
